### PR TITLE
Milestone 2 pull request

### PR DESCRIPTION
**Pull request by sim2kid**

### CODE REVIEW

**Comment by swarmsoflizards** [comment]
| Needs Improvement | Fair | Excellent | Notes
-- | -- | -- | -- | --
What was your overall impression of the playthrough? | Disorienting, confusing and/or not functional | Able to traverse the space but felt somewhat disorienting | Excellent use of space, environment and light | Space was very small but clearly readable, if empty
Was all the geometry / terrain / set pieces textured or have vertex color painting? | Little to no objects were textured / painted | Some of the objects were textured / painted | All the objects were textured / painted | Every object was textured in all four levels
Were you able to get some context about the world through the geometry/terrain, textures and set pieces? | Clues to the setting were not clear and I would not be able to discern without being told | Some objects gave me a little insight and I would be to make some educated guesses if I wasn't told | I had a good idea of the setting merely by observing the game space and would feel confident about guessing without direction | Some context; furniture and space clearly gave context, but there are very few objects in the space
Was the space properly lit? | No, I was barely able to play because of the lighting / lack of lighting | Certain areas were properly lit well but others were not | The lighting was excellent and even helped guide me through the level | There was some trouble with the lighting, but it was mostly effective. There were a couple of areas where the lighting guided me, but it was mostly set-dressing.
Did the areas feel spaced out proportionally to the player character? | No, the space felt too crowded or too empty | Certain areas felt proportional but others did not | The spacing was excellent and had good flow | Spacing was mostly proportional; second level was very confusing but others were all parsable
Was the playthrough functional? | No, I was barely or unable to play due | I ran into some performance issues and/or even may have needed to restart | Yes! The game ran smoothly and there were no bugs | No issues with running or bugs at all

**Comment by VinylKnight** [comment]
| Needs Improvement | Fair | Excellent | Notes
-- | -- | -- | -- | --
What was your overall impression of the playthrough? | Disorienting, confusing and/or not functional | Able to traverse the space but felt somewhat disorienting | Excellent use of space, environment and light | Most of the rooms had purpose and direction you knew for the most part which way to go and movement isn’t restrained.
Was all the geometry / terrain / set pieces textured or have vertex color painting? | Little to no objects were textured / painted | Some of the objects were textured / painted | All the objects were textured / painted | Most assets and locations were textured but there was a table and stairs that did not appear to have a texture.
Were you able to get some context about the world through the geometry/terrain, textures and set pieces? | Clues to the setting were not clear and I would not be able to discern without being told | Some objects gave me a little insight and I would be to make some educated guesses if I wasn't told | I had a good idea of the setting merely by observing the game space and would feel confident about guessing without direction | I had a distinct  and clear idea of what each locations was the second area was a location that made me slightly unsure because it could be interpreted as a test chamber or an interrogation room
Was the space properly lit? | No, I was barely able to play because of the lighting / lack of lighting | Certain areas were properly lit well but others were not | The lighting was excellent and even helped guide me through the level | All the rooms were lit but Unity was causing issues with the lights not allowing for each area to be properly lit. Each area had a sufficient amount of light sources.
Did the areas feel spaced out proportionally to the player character? | No, the space felt too crowded or too empty | Certain areas felt proportional but others did not | The spacing was excellent and had good flow | Every area had adequate room to move. The second area had a collision problem with one table but all other aspects were fine.
Was the playthrough functional? | No, I was barely or unable to play due | I ran into some performance issues and/or even may have needed to restart | Yes! The game ran smoothly and there were no bugs | The playthrough went smoothly. Progress was uninterrupted and allowed me to move about the areas perfectly fine.

**Review by VinylKnight — APPROVED** [review]
Everything seems to be fine just some minor repairs on the lighting. Good Job on each individual area.

**Comment by jadlerfisher** [comment]
Good.

**Comment by sim2kid** [comment]
Merged, request closed

**Pull request merged**
